### ISSUE TITLE
Add code to generate the temperature-dependency datasets

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/climateR0#7]
Thanks for your work on this package!

The main limitation (and probably the next priority) at the moment as far as I can tell is that there is no easy way for users to generate the R-temperature datasets (data in `inst/extdata`) for a pathogen that may not have been included in the initial analysis.

Instead of / in addition to providing the already computed data, it would be very useful to have functions to generate this data. It would allow creating new datasets with your method, and understanding how the existing datasets are been created.

I understand it may be challenging to figure out how to make this fit into a package. If this is a problem, providing the scripts as vignettes would be a first very useful step.

**Comment by EmilieFinch** [comment]
Hello! So generating R0-temperature datasets for other pathogens is currently beyond the scope of this package. Here, we use the results from a large body of work by [Mordecai et al](https://onlinelibrary.wiley.com/doi/10.1111/ele.13335) which synthesises data from constant temperature experiments (i.e. experiments where temperature is varied and the effect on a vector trait is measured) and then combines the results to output modelled R0 for different vector-pathogen combinations. 

The aim for this package was to simplify the extraction and interpolation of these temperature-R0 curves for a user with their own temperature data. The posterior estimates used here were made available to us in [this repo](https://github.com/mshocket/Thermal-Eco-MBD/tree/main/R0%20Trajectories). I believe there's other work going on (by Leah Johnson and others) on other tools in this area which might be good to link up with later down the line - happy to chat about this further if helpful.
